spring.application.name=expovigia

spring.datasource.url=jdbc:postgresql://localhost:5432/expovigia
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public

server.port=8080

logging.level.org.flywaydb=DEBUG

ocr.client.base-url=${OCR_CLIENT_BASE_URL:http://localhost:8090}
ocr.client.endpoint=${OCR_CLIENT_ENDPOINT:/ocr/plate}
ocr.client.connect-timeout-ms=${OCR_CLIENT_CONNECT_TIMEOUT_MS:1500}
ocr.client.read-timeout-ms=${OCR_CLIENT_READ_TIMEOUT_MS:3500}
